[functions.player-headshot]
verify_jwt = false

[functions.nba-rosters]
verify_jwt = false

[functions.gleague-rosters]
verify_jwt = false

[functions.export-image]
verify_jwt = false

[functions.game-analysis]
verify_jwt = false

[functions.pregame-scouting]
verify_jwt = false
