-- Compact, season-aware facts used by the officiating matchup insight engine.
-- Simulator runs are intentionally not persisted. Only production report output
-- may be cached in nba_officiating_insight_reports.

create table if not exists public.nba_team_game_facts (
  id bigint generated by default as identity primary key,
  season text not null,
  season_type text not null,
  game_id text not null,
  game_date date not null,
  team_id text not null,
  team text not null,
  opponent_team_id text,
  opponent text not null,
  home_away text not null check (home_away in ('home', 'away')),
  won boolean,
  minutes numeric,
  points integer,
  opponent_points integer,
  possessions_estimate numeric,
  field_goals_attempted integer,
  three_pointers_attempted integer,
  free_throws_attempted integer,
  rebounds_offensive integer,
  turnovers integer,
  personal_fouls integer,
  technical_fouls integer,
  points_in_paint integer,
  points_fast_break integer,
  points_second_chance integer,
  source text not null default 'nba_live_boxscore',
  source_version text not null default 'v1',
  source_hash text,
  completeness_status text not null default 'complete',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_id, team_id)
);

create index if not exists nba_team_game_facts_season_team_date
on public.nba_team_game_facts (season, team, game_date desc);

create index if not exists nba_team_game_facts_season_game
on public.nba_team_game_facts (season, game_id);

create table if not exists public.nba_player_game_facts (
  id bigint generated by default as identity primary key,
  season text not null,
  season_type text not null,
  game_id text not null,
  game_date date not null,
  team_id text not null,
  team text not null,
  opponent text not null,
  player_id text not null,
  player_name text not null,
  minutes numeric,
  points integer,
  field_goals_attempted integer,
  three_pointers_attempted integer,
  free_throws_attempted integer,
  rebounds_offensive integer,
  assists integer,
  turnovers integer,
  personal_fouls integer,
  technical_fouls integer,
  points_in_paint integer,
  source text not null default 'nba_live_boxscore',
  source_version text not null default 'v1',
  source_hash text,
  completeness_status text not null default 'complete',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_id, player_id)
);

create index if not exists nba_player_game_facts_season_player_date
on public.nba_player_game_facts (season, player_id, game_date desc);

create index if not exists nba_player_game_facts_season_team_date
on public.nba_player_game_facts (season, team, game_date desc);

create table if not exists public.nba_official_game_facts (
  id bigint generated by default as identity primary key,
  season text not null,
  season_type text not null,
  game_id text not null,
  game_date date not null,
  home_team text not null,
  away_team text not null,
  official_id text not null,
  official_name text not null,
  role_key text,
  assignment_order integer,
  is_alternate boolean not null default false,
  calls integer not null default 0,
  fouls integer not null default 0,
  violations integer not null default 0,
  technicals integer not null default 0,
  category_counts jsonb not null default '{}'::jsonb,
  team_net_calls jsonb not null default '{}'::jsonb,
  source_version text not null default 'v1',
  completeness_status text not null default 'complete',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_id, official_id)
);

create index if not exists nba_official_game_facts_season_official_date
on public.nba_official_game_facts (season, official_id, game_date desc);

create index if not exists nba_official_game_facts_season_game
on public.nba_official_game_facts (season, game_id);

create table if not exists public.nba_officiating_insight_reports (
  id bigint generated by default as identity primary key,
  game_id text not null,
  season text not null,
  crew_ids text[] not null,
  evidence_hash text not null,
  prompt_version text not null,
  payload jsonb not null,
  generated_at timestamptz not null default now(),
  unique (game_id, evidence_hash, prompt_version)
);

create index if not exists nba_officiating_insight_reports_game
on public.nba_officiating_insight_reports (game_id, generated_at desc);

create table if not exists public.nba_officiating_insight_feedback (
  id bigint generated by default as identity primary key,
  candidate_id text not null,
  family text,
  official_id text,
  verdict text not null check (verdict in ('Useful', 'Not useful', 'Wrong', 'Repetitive', 'Too obvious')),
  note text,
  insight_text text,
  evidence jsonb not null default '{}'::jsonb,
  context jsonb not null default '{}'::jsonb,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists nba_officiating_insight_feedback_candidate
on public.nba_officiating_insight_feedback (candidate_id, created_at desc);

create index if not exists nba_officiating_insight_feedback_verdict
on public.nba_officiating_insight_feedback (verdict, created_at desc);

alter table public.nba_team_game_facts enable row level security;
alter table public.nba_player_game_facts enable row level security;
alter table public.nba_official_game_facts enable row level security;
alter table public.nba_officiating_insight_reports enable row level security;
alter table public.nba_officiating_insight_feedback enable row level security;

drop policy if exists "team game facts visible to authenticated users" on public.nba_team_game_facts;
create policy "team game facts visible to authenticated users"
on public.nba_team_game_facts for select to authenticated using (true);

drop policy if exists "player game facts visible to authenticated users" on public.nba_player_game_facts;
create policy "player game facts visible to authenticated users"
on public.nba_player_game_facts for select to authenticated using (true);

drop policy if exists "official game facts visible to authenticated users" on public.nba_official_game_facts;
create policy "official game facts visible to authenticated users"
on public.nba_official_game_facts for select to authenticated using (true);

drop policy if exists "officiating insight reports visible to authenticated users" on public.nba_officiating_insight_reports;
create policy "officiating insight reports visible to authenticated users"
on public.nba_officiating_insight_reports for select to authenticated using (true);

drop policy if exists "officiating insight feedback insertable by authenticated users" on public.nba_officiating_insight_feedback;
create policy "officiating insight feedback insertable by authenticated users"
on public.nba_officiating_insight_feedback for insert to authenticated with check (created_by = auth.uid() or created_by is null);

drop policy if exists "officiating insight feedback visible to admins" on public.nba_officiating_insight_feedback;
create policy "officiating insight feedback visible to admins"
on public.nba_officiating_insight_feedback for select to authenticated using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
      and profiles.status = 'active'
  )
);
