create table if not exists public.nba_officiating_insight_feedback (
  id bigint generated by default as identity primary key,
  candidate_id text not null,
  family text,
  official_id text,
  verdict text not null check (verdict in ('Useful', 'Not useful', 'Wrong', 'Repetitive', 'Too obvious')),
  note text,
  insight_text text,
  evidence jsonb not null default '{}'::jsonb,
  context jsonb not null default '{}'::jsonb,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists nba_officiating_insight_feedback_candidate
on public.nba_officiating_insight_feedback (candidate_id, created_at desc);

create index if not exists nba_officiating_insight_feedback_verdict
on public.nba_officiating_insight_feedback (verdict, created_at desc);

alter table public.nba_officiating_insight_feedback enable row level security;

drop policy if exists "officiating insight feedback insertable by authenticated users" on public.nba_officiating_insight_feedback;
create policy "officiating insight feedback insertable by authenticated users"
on public.nba_officiating_insight_feedback for insert to authenticated with check (created_by = auth.uid() or created_by is null);

drop policy if exists "officiating insight feedback visible to admins" on public.nba_officiating_insight_feedback;
create policy "officiating insight feedback visible to admins"
on public.nba_officiating_insight_feedback for select to authenticated using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
      and profiles.status = 'active'
  )
);
