-- Apply after supabase/officiating_intelligence.sql.
-- Keeps Officiating browser reads authenticated.

drop policy if exists nba_official_game_assignments_select_public on public.nba_official_game_assignments;
drop policy if exists nba_official_game_assignments_select_authenticated on public.nba_official_game_assignments;
create policy nba_official_game_assignments_select_authenticated
on public.nba_official_game_assignments
for select
to authenticated
using (true);

drop policy if exists nba_official_call_events_select_public on public.nba_official_call_events;
drop policy if exists nba_official_call_events_select_authenticated on public.nba_official_call_events;
create policy nba_official_call_events_select_authenticated
on public.nba_official_call_events
for select
to authenticated
using (true);

drop policy if exists nba_coach_challenge_events_select_public on public.nba_coach_challenge_events;
drop policy if exists nba_coach_challenge_events_select_authenticated on public.nba_coach_challenge_events;
create policy nba_coach_challenge_events_select_authenticated
on public.nba_coach_challenge_events
for select
to authenticated
using (true);

drop policy if exists nba_officiating_event_reviews_select_public on public.nba_officiating_event_reviews;
drop policy if exists nba_officiating_event_reviews_select_authenticated on public.nba_officiating_event_reviews;
create policy nba_officiating_event_reviews_select_authenticated
on public.nba_officiating_event_reviews
for select
to authenticated
using (true);

drop policy if exists nba_challenge_context_tags_select_public on public.nba_challenge_context_tags;
drop policy if exists nba_challenge_context_tags_select_authenticated on public.nba_challenge_context_tags;
create policy nba_challenge_context_tags_select_authenticated
on public.nba_challenge_context_tags
for select
to authenticated
using (true);

drop policy if exists nba_challenge_context_event_tags_select_public on public.nba_challenge_context_event_tags;
drop policy if exists nba_challenge_context_event_tags_select_authenticated on public.nba_challenge_context_event_tags;
create policy nba_challenge_context_event_tags_select_authenticated
on public.nba_challenge_context_event_tags
for select
to authenticated
using (true);
